### ISSUE TITLE
Unable to use segments

### ISSUE THREAD

**Issue by lloydnye** [Flagsmith/flagsmith#35] opened 2019-12-09 10:52 UTC
Hi I've been attempting to self host the bullet train api and frontend, and have some success, but am having issues with segments. 

After creating a segment with the front end, I can't select a segment override when editing a feature. The dropdown is visible but contains no values and is unresponsive. 

![image](https://user-images.githubusercontent.com/11163083/70429637-e93d7600-1a70-11ea-8fad-b60b28336b70.png)

**Setup**
I have forked the api and frontend, and deployed them to heroku. 
For the api I have set the DATABASE and appropriate DJANGO env vars and it seems to be working as expected. 

For the frontend, I modified the api url to point to my backend, and set ENV to prod in the heroku env vars. 

I also changed the assetUrl in `project_prod.js` to point to my deployed heroku app and added a build command to the package json so that heroku will build it. `"build": "npm run env && npm run bundle",`

Any suggestions or something I'm missing?

**Comment by piyushkmr** [comment] 2020-04-01 11:22
I am also facing this issue, I am using tag 2.0 for frontend and 1.9 for backend.

**Comment by matthewelwell** [comment] 2020-04-05 18:22
Hi @piyushkmr could you try checking out the latest versions of frontend and backend and see if you still get the same issues?

**Comment by mariusbogdanescu** [comment] 2020-04-09 07:06
I am having the same issue with latest code from master branch.

**Comment by matthewelwell** [comment] 2020-04-09 08:18
@mariusbogdanescu have you updated both the frontend and backend?

**Comment by mariusbogdanescu** [comment] 2020-04-09 08:21
Yes, I just tried a pull this morning and they were both up to date.

**Comment by matthewelwell** [comment] 2020-04-09 08:21
Ok, thanks. I'll look into this further for you.

**Comment by kyle-ssg** [comment] 2020-04-09 12:15
It looks like there's 2 separate issues here, so I'll address the segments issue as I think I can potentially see the cause.

We use Bullet Train to manage features we rollout, if you are using your own bullet train environment (i.e. by editing project_x.js-> bulletTrain) then you will need to have a replica of our flags.

I'll add this to the docs to clear any miss understanding here, here are the flags we are using at the moment https://gist.github.com/kyle-ssg/4c65b4185d0fe3ae35f73244de5e2fef. In particular, you'll need a flag in your bullet train project that matches segment_operators.

Hopefully this makes sense and fixes your issue.

**Comment by kyle-ssg** [comment] 2020-06-01 18:26
Closing this, as of 2.1 the versioning should be a lot more clear as we're keeping backend and frontend in sync. Please create a new issue if you're still having problems.

**Closed as completed by kyle-ssg** 2020-06-01 18:26 UTC
