### ISSUE TITLE
301 Moved Permanently when following swagger docs

### ISSUE THREAD

**Issue by edumucelli** [Flagsmith/flagsmith#75] opened 2021-02-12 15:32 UTC
The swagger docs are cool, thanks. When giving it a try on the `segments` API it generated me the following `curl` command:

```
curl -X GET "http://api.flagsmith.com/api/v1/segments/?page=1" -H  "accept: application/json" -H  "X-CSRFToken: GsV6WkSPliMSr2tzWoJpTsbnPPwOHdR7GZmkCO7MtsOzCBEwbDBAsRoaIQuR13aV"
```
It will return a 

```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```
That is because you guys are using `https` now (since this doc has generated).

The fix is just replace the `http` by `https` in the doc. I can make a PR to fix, just guide me where this is generated.

**Comment by dabeeeenster** [comment] 2021-02-12 15:47
Hmm it looks like this is due to the API running behind a proxy and drf-yasg/django not picking this up correctly. We do have 

`SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")`

set in our settings, so not sure what might be causing this. It doesn't look like it is going to be a simple fix!

**Comment by edumucelli** [comment] 2021-02-12 15:52
I see. Once I replaced `http` with `https` I had a different error, but at least the redirection has passed:

```
curl -X GET "https://api.flagsmith.com/api/v1/segments/?page=1" -H  "accept: application/json" -H  "X-CSRFToken: GsV6WkSPliMSr2tzWoJpTsbnPPwOHdR7GZmkCO7MtsOzCBEwbDBAsRoaIQuR13aV"
```

```
{"detail":"Invalid or missing Environment Key"}
```

**Comment by dabeeeenster** [comment] 2021-02-12 15:58
Ah - it looks like that's a deprecated endpoint - will get that removed

Try `/projects/{project_pk}/segments/`

**Comment by edumucelli** [comment] 2021-02-12 16:16
Thanks for the prompt response: is `project_pk` the project "name" we give in the interface as below or something else?
![name](https://user-images.githubusercontent.com/959623/107792711-591e4f00-6d4d-11eb-871e-d6d2ce330575.png)

In this case I am running on my local environment, should it be:

```
curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Environment-Key: MY_ENV_KEY" http://localhost:8080/api/projects/ua/segments/
```
I am having a 404 for that:

```
HTTP/1.1 404 Not Found
X-Powered-By: Express
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 164
Date: Fri, 12 Feb 2021 16:14:37 GMT
Connection: keep-alive
Keep-Alive: timeout=5

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/projects/ua/segments/</pre>
</body>
</html>
```

**Comment by dabeeeenster** [comment] 2021-02-12 16:27
`project_pk` is the ID provided by the database - it will be in your address bar if you a viewing an environment.

**Comment by edumucelli** [comment] 2021-02-12 16:45
I see, thanks for the clarification. Sorry for the series of questions for what seems to be a simple setup. 

The URL when in the features dashboard: `http://localhost:8080/project/1/environment/m2U2moyvjqeK2LdSkkWtxG/features`

```
curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Environment-Key: m2U2moyvjqeK2LdSkkWtxG" http://localhost:8080/api/projects/1/segments/
```

Still 404. I have tried to look for the logs inside container, but I could not find it. From the container `logs -f` nothing in the logs that helped.

Related question: I am really interested in the segments, as they give the possibility for the progressive rollout AFAIK. I have seen they are not yet implemented on the Go client. I am wondering, hypothetically if one would add support to Segments in such client s/he would have to pass project database id?

**Comment by dabeeeenster** [comment] 2021-02-12 16:48
How are you running the API? It looks like you might be pointing `curl` at the front end and not the API? 

Also you will need a token to hit those endpoints: https://docs.flagsmith.com/system-administration/#generating-an-admin-api-token-for-your-environment

Segments are not sent to the client SDKs by design. They are just used to compute flag values. 

Happy to have a call next week if that would help?

**Comment by edumucelli** [comment] 2021-02-12 17:03
Running using `docker-compose`:

```
       Name                     Command              State           Ports         
-----------------------------------------------------------------------------------
flagsmith_api        ./bin/docker                    Up      0.0.0.0:8000->8000/tcp
flagsmith_frontend   sh ./bin/docker/run-docker.sh   Up      0.0.0.0:8080->8080/tcp
flagsmith_influxdb   /entrypoint.sh influxd          Up      0.0.0.0:8086->8086/tcp
flagsmith_postgres   docker-entrypoint.sh postgres   Up      5432/tcp      
```
I am actually pointing  the curl to the `API` because I can 

```
curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Environment-Key: m2U2moyvjqeK2LdSkkWtxG" http://localhost:8080/api
```
It returns `{"message":"API is up and running!"}`.

From that I am exploring the endpoints I have seen in the [swagger](https://api.flagsmith.com/api/v1/docs/) docs. Given I am interested in the progressive rollout (basically %split) I have created a Segment and wanted to make some queries against this segment by `ID` (the string key naming the segment) so that I could see that they were going % of the time to enabled/disabled.

When using the [Go](https://github.com/Flagsmith/flagsmith-go-client/blob/master/client.go) client I saw it was not able to handle Segments, so I was interested on understanding how it works, and maybe adding support to it myself if necessary and ok.

Sure, we can discuss in further details on a call if you prefer.

**Comment by dabeeeenster** [comment] 2021-02-15 09:31
Hi Eduardo,

Can you email support@flagsmith.com and we can set up a time? Thanks!

**Closed as completed by dabeeeenster** 2021-02-15 09:31 UTC
